steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - eval docker login -u $_DOCKER_PASSWORD -p $_DOCKER_PASSWORD
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - TAG_NAME=$SHORT_SHA
      - -t
      - chamodshehanka/a-container:$SHORT_SHA
      - -f
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push chamodshehanka/a-container:$SHORT_SHA
  - name: gcr.io/cloud-builders/curl
    entrypoint: curl
    args:
      - --header
      - "x-organization-id: c569bcc5-3d17-4a08-a77b-693d841360c6"
      - --header
      - "x-project-id: b9bb816b-cf68-43c7-bddc-a92ea9f7743b"
      - -d
      - '{ "channel": "default",  "update_type": "patch", "container_id":
        e67d840a-40ad-4021-b5a7-f7bdb7d198f2,  "image_name_with_tag":
        "chamodshehanka/a-container:$SHORT_SHA"}'
      - -X
      - POST
      - https://ambassador.dev.platformer.com/rudder/webhook/v1/container?token=${_PLATFORMER_AUTOGENERATED_CICD}
images: []
