name: Docker

on:
  push:
    branches:
      - main

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: a-container

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - uses: Industrial/push-docker-gcr
        with:
          docker_image_name: $IMAGE_NAME
          docker_image_tag: latest
          docker_context: .
          gcr_host: gcr.io/platformer-november/a-container
          gcr_project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          gcr_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
